description: "Two thousand years ago, the Roman Empire ruled the lands around the Mediterranean Sea. With peace at the borders, harmony inside the provinces, uniform law, and a common currency, the economy thrived and gave rise to mighty Roman dynasties as they expanded throughout the numerous cities. Guide one of these dynasties and send colonists to the remote realms of the Empire; develop your trade network; and appease the ancient gods for their favor &mdash; all to gain the chance to emerge victorious!<br/><br/>Concordia is a peaceful strategy game of economic development in Roman times for 2-5 players aged 13 and up. Instead of looking to the luck of dice or cards, players must rely on their strategic abilities. Be sure to watch your rivals to determine which goals they are pursuing and where you can outpace them! In the game, colonists are sent out from Rome to settle down in cities that produce bricks, food, tools, wine, and cloth. Each player starts with an identical set of playing cards and acquires more cards during the game. These cards serve two purposes:<br/><br/><br/>    They allow a player to choose actions during the game.<br/>    They are worth victory points (VPs) at the end of the game. <br/><br/><br/>Concordia is a strategy game that requires advance planning and consideration of your opponent's moves. Every game is different, not only because of the sequence of new cards on sale but also due to the modular layout of cities. (One side of the game board shows the entire Roman Empire with 30 cities for 3-5 players, while the other shows Roman Italy with 25 cities for 2-4 players.) When all cards have been sold or after the first player builds his 15th house, the game ends. The player with the most VPs from the gods (Jupiter, Saturnus, Mercurius, Minerva, Vesta, etc.) wins the game.<br/><br/>",
name: "Concordia",
userId: "5bf48c4622473c3fc0240942",
objectId: 124361,
minPlayers: 2,
maxPlayers: 5,
playingTime: 100,
yearPublished: 2013,
image: "https://cf.geekdo-images.com/original/img/abKLQBfHHaouqsLx7GGiIzqXBu8=/0x0/pic3453267.jpg",
thumbnail: "https://cf.geekdo-images.com/thumb/img/Ap4Vj-Gb0Z64bxDUf7ulr52rFMw=/fit-in/200x150/pic3453267.jpg",
boardgameMechanic: ["Card Drafting", "Deck / Pool Building", "Hand Management", "Point to Point Movement"],
usersRated: 17432,
averageRating: 8.08625,
numOfWeights: 779,
averageWeight: 3.0924,
bggLink: "https://boardgamegeek.com/boardgame/124361"